version: 2

jobs:
  checkstyle:
    docker:
      - image: ubuntu:focal

    environment:
      WM_NCOMPPROCS: 2
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive

    working_directory: /root/sedfoam
    steps:
      - run:
          name: Make project and user dir
          command: mkdir -p /root/sedfoam

      - checkout:
          path: /root/sedfoam

      - run:
          name: Install vera++
          command: >
            apt-get update &&
            apt-get install -y ca-certificates git vera++

      - run:
          name: pull checkStyle submodule
          command: >
            shopt -s expand_aliases &&
            git submodule init &&
            git submodule update --remote

      - run:
          name: Check style
          command: >
            shopt -s expand_aliases &&
            ./foamStyleCheck/checkStyle

  docs-build:
    docker:
      - image: opencfd/openfoam2106-dev

    environment:
      WM_NCOMPPROCS: 2
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive

    working_directory: /root/sedfoam
    steps:
      - run:
          name: Install docs packages
          command: >
            update-ca-certificates &&
            apt-get update && apt-get -y install ca-certificates git python3-pip dvisvgm libclang-9-dev &&
            apt-get -y install ack-grep libclang-cpp9 wget graphviz tex-gyre texlive-base &&
            apt-get -y install texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended

      - run:
          name: Install python packages
          command: >
            shopt -s expand_aliases && python3 --version &&
            pip3 --version &&
            pip3 install -U jinja2 Pygments

      - run:
          name: Make project and user dir
          command: mkdir -p /root/sedfoam

      - checkout:
          path: /root/sedfoam

      - run:
          name: install doxygen 1.9.3
          command: >
            shopt -s expand_aliases &&
            wget https://sourceforge.net/projects/doxygen/files/rel-1.9.3/doxygen-1.9.3.linux.bin.tar.gz &&
            tar -xvf doxygen-1.9.3.linux.bin.tar.gz

      - run:
          name: clone m.css and build doc
          command: >
            shopt -s expand_aliases &&
            export PATH=$PWD/doxygen-1.9.3/bin:$PATH &&
            cd doc &&
            git clone git@github.com:mosra/m.css &&
            cd m.css/documentation && cp ../../doxygen.py . &&
            source /openfoam/bash.rc &&
            python3 doxygen.py ../../conf.py &&
            cd ../.. && cp images/* mcssout/html/. &&
            ack "ource file" -l --print0 | xargs -0 -n 1 sed -i "s/\"\/root\/sedfoam/\"https:\/\/github.com\/sedfoam\/sedfoam\/blob\/master/g"

      - persist_to_workspace:
          root: /root/sedfoam/doc/mcssout
          paths: html

  docs-deploy:
    docker:
      - image: node:17.8.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "eduard.puig-montella@univ-grenoble-alpes.fr"
            git config user.name "puigmontella"
      - add_ssh_keys:
          fingerprints:
           - "4c:c1:19:ef:cd:1f:dc:5d:0b:3d:62:8e:21:64:22:e7"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html

